[package]
name = "ransonware"
version = "0.1.0"
edition = "2021"

[dependencies]
procfs = "0.16.0"
libc = "0.2"
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_12"] }
gdk = "0.13.2"
gdk-pixbuf = "0.9.0"
sys-info = "0.8"


aes = "0.7"
cipher = "0.4"
rand = "0.8"
block-padding = "0.3"

